env:
  - CGO_ENABLED=0

builds:
  - main: ./cmd/fdlr
    binary: fdlr
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
