name: go

on:
- push
- pull_request

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
        go-version: [1.16.x]
    runs-on: ${{ matrix.platform }}
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Linting & vetting.
        run: make lint

      - name: Formatting.
        run: make format
